name: Changelog CI

on:
  pull_request:
    branches: ["develop", "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: rjgill/changelog-ci@test
        with:
          config_file: .github/workflows/.changelog-ci-config.json
